from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime
import io

def generate_report_pdf(prediction_data: dict, patient_name: str = "Patient") -> bytes:
    """Generate professional medical report PDF"""
    
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=0.5*inch)
    
    story = []
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#667eea'),
        spaceAfter=30,
        alignment=TA_CENTER
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#667eea'),
        spaceAfter=12,
        spaceBefore=12
    )
    
    # Title
    story.append(Paragraph("EyeTrust AI - Medical Report", title_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Report info
    report_date = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    story.append(Paragraph(f"<b>Report Date:</b> {report_date}", styles['Normal']))
    story.append(Paragraph(f"<b>Patient:</b> {patient_name}", styles['Normal']))
    story.append(Spacer(1, 0.3*inch))
    
    # Diagnosis
    story.append(Paragraph("Diagnosis Results", heading_style))
    
    pred = prediction_data['prediction']
    disease = pred['predicted_class']
    confidence = round(pred['confidence'] * 100, 2)
    
    diagnosis_data = [
        ['Detected Condition:', disease],
        ['Confidence Level:', f"{confidence}%"],
        ['Status:', 'Normal' if pred['is_normal'] else 'Requires Attention']
    ]
    
    diagnosis_table = Table(diagnosis_data, colWidths=[2.5*inch, 3.5*inch])
    diagnosis_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e8eaf6')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey)
    ]))
    
    story.append(diagnosis_table)
    story.append(Spacer(1, 0.3*inch))
    
    # All Predictions
    story.append(Paragraph("Detailed Analysis", heading_style))
    
    prob_data = [['Disease', 'Probability']]
    for disease, prob in pred['all_probabilities'].items():
        prob_data.append([disease, f"{round(prob * 100, 2)}%"])
    
    prob_table = Table(prob_data, colWidths=[3*inch, 3*inch])
    prob_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#667eea')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 14),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    story.append(prob_table)
    story.append(Spacer(1, 0.3*inch))
    
    # AI Advice
    story.append(Paragraph("AI Doctor's Recommendations", heading_style))
    advice_text = prediction_data.get('ai_advice', 'No advice available')
    story.append(Paragraph(advice_text, styles['Normal']))
    story.append(Spacer(1, 0.3*inch))
    
    # Disclaimer
    story.append(Spacer(1, 0.5*inch))
    disclaimer_style = ParagraphStyle(
        'Disclaimer',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.red,
        alignment=TA_CENTER
    )
    story.append(Paragraph(
        "<b>MEDICAL DISCLAIMER:</b> This report is generated by an AI system for educational purposes only. "
        "Always consult a licensed ophthalmologist for professional medical advice, diagnosis, and treatment.",
        disclaimer_style
    ))
    
    # Build PDF
    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    
    return pdf_bytes